version: 2
jobs:
  build:
    docker:
      - image: mikoto2000/sphinx
    working_directory: ~/doc
    steps:
      - checkout
      - run:
          name: Build html
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              DIR='latest'
            else
              DIR='develop'
            fi
            
            python3 -m pip install sphinx_rtd_theme
            rm -rf docs/${DIR}/html
            cd doc
            make html BUILDDIR=../docs/${DIR}
            cd ..;rm -rf docs/${DIR}/doctrees
      - persist_to_workspace:
          root: ~/doc
          paths:
            - ./*
  publish:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: doc
      - run:
          name: config
          command: |
            git config --global user.email "keel@tis.co.jp"
            git config --global user.name "keel-dev"
      - add_ssh_keys:
          fingerprints:
            - "ab:b2:ee:ac:97:b9:63:99:60:d9:30:f9:15:25:9c:5d"
      - run:
          working_directory: doc
          name: deploy
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              DIR='latest'
            else
              DIR='develop'
            fi

            git add docs --all
            git stash
            git checkout master
            rm -rf docs/${DIR}/html
            git add docs --all
            git commit -m '[ci skip] publish new version'
            git stash pop
            git commit --amend -m '[ci skip] publish new version'
            git push origin master            
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: [master,develop]
      - publish:
          requires:
            - build
          filters:
            branches:
              only: [master,develop]

